"""Initial migration: create all tables

Revision ID: e6f9f2446064
Revises: 
Create Date: 2025-11-09 12:36:27.197354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f9f2446064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_binary', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('compression', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_contents_content_hash'), 'file_contents', ['content_hash'], unique=True)
    op.create_index(op.f('ix_file_contents_reference_count'), 'file_contents', ['reference_count'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('os_type', sa.String(length=20), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('working_directory', sa.Text(), nullable=True),
    sa.Column('total_locations', sa.Integer(), nullable=False),
    sa.Column('files_found', sa.Integer(), nullable=False),
    sa.Column('directories_found', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('changed_from_previous', sa.Integer(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('parent_snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_snapshot_hash'), 'snapshots', ['snapshot_hash'], unique=True)
    op.create_index(op.f('ix_snapshots_snapshot_time'), 'snapshots', ['snapshot_time'], unique=False)
    op.create_table('snapshot_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('path_template', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('old_content_hash', sa.String(length=64), nullable=True),
    sa.Column('new_content_hash', sa.String(length=64), nullable=True),
    sa.Column('old_size_bytes', sa.Integer(), nullable=True),
    sa.Column('new_size_bytes', sa.Integer(), nullable=True),
    sa.Column('old_modified_time', sa.DateTime(), nullable=True),
    sa.Column('new_modified_time', sa.DateTime(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changes_snapshot', 'snapshot_changes', ['snapshot_id'], unique=False)
    op.create_index('idx_changes_type', 'snapshot_changes', ['change_type'], unique=False)
    op.create_table('snapshot_env_vars',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('placeholder', sa.String(length=100), nullable=False),
    sa.Column('resolved_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'placeholder'),
    sa.UniqueConstraint('snapshot_id', 'placeholder', name='uq_snapshot_env_var')
    )
    op.create_table('snapshot_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path_template', sa.Text(), nullable=False),
    sa.Column('resolved_path', sa.Text(), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('accessed_time', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.String(length=20), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['file_contents.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_paths_exists', 'snapshot_paths', ['exists'], unique=False)
    op.create_index('idx_snapshot_paths_hash', 'snapshot_paths', ['content_hash'], unique=False)
    op.create_index('idx_snapshot_paths_snapshot', 'snapshot_paths', ['snapshot_id'], unique=False)
    op.create_index('idx_snapshot_paths_template', 'snapshot_paths', ['path_template'], unique=False)
    op.create_table('snapshot_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name', name='uq_tag_name')
    )
    op.create_index('idx_tags_name', 'snapshot_tags', ['tag_name'], unique=False)
    op.create_index('idx_tags_snapshot', 'snapshot_tags', ['snapshot_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_path_id', sa.Integer(), nullable=True),
    sa.Column('annotation_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('annotation_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_path_id'], ['snapshot_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claude_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_path_id', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=False),
    sa.Column('num_projects', sa.Integer(), nullable=True),
    sa.Column('num_mcp_servers', sa.Integer(), nullable=True),
    sa.Column('num_startups', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.Integer(), nullable=True),
    sa.Column('largest_project_path', sa.Text(), nullable=True),
    sa.Column('largest_project_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_path_id'], ['snapshot_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_path_id')
    )
    op.create_table('json_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_path_id', sa.Integer(), nullable=False),
    sa.Column('json_path', sa.Text(), nullable=False),
    sa.Column('json_value', sa.Text(), nullable=True),
    sa.Column('json_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['file_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_path_id'], ['snapshot_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_json_path', 'json_data', ['json_path'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_path_id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('env', sa.Text(), nullable=True),
    sa.Column('working_directory', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_path_id'], ['snapshot_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_snapshot', 'mcp_servers', ['snapshot_path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mcp_snapshot', table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index('idx_json_path', table_name='json_data')
    op.drop_table('json_data')
    op.drop_table('claude_configs')
    op.drop_table('annotations')
    op.drop_index('idx_tags_snapshot', table_name='snapshot_tags')
    op.drop_index('idx_tags_name', table_name='snapshot_tags')
    op.drop_table('snapshot_tags')
    op.drop_index('idx_snapshot_paths_template', table_name='snapshot_paths')
    op.drop_index('idx_snapshot_paths_snapshot', table_name='snapshot_paths')
    op.drop_index('idx_snapshot_paths_hash', table_name='snapshot_paths')
    op.drop_index('idx_snapshot_paths_exists', table_name='snapshot_paths')
    op.drop_table('snapshot_paths')
    op.drop_table('snapshot_env_vars')
    op.drop_index('idx_changes_type', table_name='snapshot_changes')
    op.drop_index('idx_changes_snapshot', table_name='snapshot_changes')
    op.drop_table('snapshot_changes')
    op.drop_index(op.f('ix_snapshots_snapshot_time'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_snapshot_hash'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_file_contents_reference_count'), table_name='file_contents')
    op.drop_index(op.f('ix_file_contents_content_hash'), table_name='file_contents')
    op.drop_table('file_contents')
    # ### end Alembic commands ###
